# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='avatar',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
