# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='city',
            field=models.CharField(choices=[(b'1', b'Aguascalientes'), (b'2', b'Baja California'), (b'3', b'Baja California Sur'), (b'4', b'Campeche'), (b'5', b'Coahuila de Zaragoza'), (b'6', b'Colima'), (b'7', b'Chiapas'), (b'8', b'Chihuahua'), (b'9', b'Distrito Federal'), (b'10', b'Durango'), (b'11', b'Guanajuato'), (b'12', b'Guerrero'), (b'13', b'Hidalgo'), (b'14', b'Jalisco'), (b'15', b'M\xc3\xa9xico'), (b'16', b'Michoac\xc3\xa1n de Ocampo'), (b'17', b'Morelos'), (b'18', b'Nayarit'), (b'19', b'Nuevo Le\xc3\xb3n'), (b'20', b'Oaxaca'), (b'21', b'Puebla'), (b'22', b'Quer\xc3\xa9taro'), (b'23', b'Quintana Roo'), (b'24', b'San Luis Potos\xc3\xad'), (b'25', b'Sinaloa'), (b'26', b'Sonora'), (b'27', b'Tabasco'), (b'28', b'Tamaulipas'), (b'29', b'Tlaxcala'), (b'30', b'Veracruz de Ignacio de la Llave'), (b'31', b'Yucat\xc3\xa1n'), (b'32', b'Zacatecas')], default='9', max_length=3),
        ),
        migrations.AddField(
            model_name='citizen',
            name='country',
            field=models.CharField(default='Mexico', max_length=50),
        ),
    ]
