# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=700)),
                ('country', models.CharField(default='Mexico', max_length=50)),
                ('city', models.CharField(choices=[(b'1', b'Aguascalientes'), (b'2', b'Baja California'), (b'3', b'Baja California Sur'), (b'4', b'Campeche'), (b'5', b'Coahuila de Zaragoza'), (b'6', b'Colima'), (b'7', b'Chiapas'), (b'8', b'Chihuahua'), (b'9', b'Distrito Federal'), (b'10', b'Durango'), (b'11', b'Guanajuato'), (b'12', b'Guerrero'), (b'13', b'Hidalgo'), (b'14', b'Jalisco'), (b'15', b'M\xc3\xa9xico'), (b'16', b'Michoac\xc3\xa1n de Ocampo'), (b'17', b'Morelos'), (b'18', b'Nayarit'), (b'19', b'Nuevo Le\xc3\xb3n'), (b'20', b'Oaxaca'), (b'21', b'Puebla'), (b'22', b'Quer\xc3\xa9taro'), (b'23', b'Quintana Roo'), (b'24', b'San Luis Potos\xc3\xad'), (b'25', b'Sinaloa'), (b'26', b'Sonora'), (b'27', b'Tabasco'), (b'28', b'Tamaulipas'), (b'29', b'Tlaxcala'), (b'30', b'Veracruz de Ignacio de la Llave'), (b'31', b'Yucat\xc3\xa1n'), (b'32', b'Zacatecas')], max_length=3)),
                ('president', models.CharField(max_length=300)),
                ('ranking', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('enabled', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=700)),
                ('country', models.CharField(default='Mexico', max_length=50)),
                ('city', models.CharField(choices=[(b'1', b'Aguascalientes'), (b'2', b'Baja California'), (b'3', b'Baja California Sur'), (b'4', b'Campeche'), (b'5', b'Coahuila de Zaragoza'), (b'6', b'Colima'), (b'7', b'Chiapas'), (b'8', b'Chihuahua'), (b'9', b'Distrito Federal'), (b'10', b'Durango'), (b'11', b'Guanajuato'), (b'12', b'Guerrero'), (b'13', b'Hidalgo'), (b'14', b'Jalisco'), (b'15', b'M\xc3\xa9xico'), (b'16', b'Michoac\xc3\xa1n de Ocampo'), (b'17', b'Morelos'), (b'18', b'Nayarit'), (b'19', b'Nuevo Le\xc3\xb3n'), (b'20', b'Oaxaca'), (b'21', b'Puebla'), (b'22', b'Quer\xc3\xa9taro'), (b'23', b'Quintana Roo'), (b'24', b'San Luis Potos\xc3\xad'), (b'25', b'Sinaloa'), (b'26', b'Sonora'), (b'27', b'Tabasco'), (b'28', b'Tamaulipas'), (b'29', b'Tlaxcala'), (b'30', b'Veracruz de Ignacio de la Llave'), (b'31', b'Yucat\xc3\xa1n'), (b'32', b'Zacatecas')], max_length=3)),
                ('licensenumber', models.CharField(max_length=300)),
                ('birthday', models.DateTimeField()),
                ('avatar', models.ImageField(upload_to='drivers_avatar')),
                ('ranking', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('enabled', models.BooleanField(default=False)),
                ('estatus', models.CharField(choices=[(b'A', b'Activo'), (b'S', b'Suspendido'), (b'R', b'Re-Incorporado'), (b'P', b'Pendiente')], default='P', max_length=1)),
                ('slug', models.SlugField(max_length=150)),
                ('cabgroupdriver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='drivers.CabGroup')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='cars.Car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
