# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='qrCode',
            new_name='qrcode',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='qrStringCode',
            new_name='qrstringCode',
        ),
    ]
