# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20161011_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='qrstringCode',
            new_name='qrstringcode',
        ),
    ]
